openapi: 3.0.0
info:
  title: Todo API
  description: REST API for the In-Memory Python Console App Todo Application
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve a list of all tasks in the system
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      description: Add a new task to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [description]
              properties:
                description:
                  type: string
                  description: The task description
                  example: "Buy groceries"
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieve a task by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The requested task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a task
      description: Modify an existing task's description
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [description]
              properties:
                description:
                  type: string
                  description: The updated task description
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a task
      description: Remove a task from the system
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{id}/complete:
    put:
      summary: Mark task as complete
      description: Change a task's status to complete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task marked as complete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{id}/incomplete:
    put:
      summary: Mark task as incomplete
      description: Change a task's status to incomplete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task marked as incomplete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      required: [id, description, status, created_date]
      properties:
        id:
          type: string
          description: Unique identifier for the task
          example: "123e4567-e89b-12d3-a456-426614174000"
        description:
          type: string
          description: The task description
          example: "Buy groceries"
        status:
          type: string
          description: Current status of the task
          enum: [incomplete, complete]
          example: "incomplete"
        created_date:
          type: string
          format: date-time
          description: Timestamp when the task was created
          example: "2023-01-01T12:00:00Z"

    Error:
      type: object
      required: [message]
      properties:
        message:
          type: string
          description: Error message
          example: "Task not found"